import copy
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from features import add_engineered_features
from models.ImprovedNeuralNetwork import ImprovedNeuralNetwork

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(f"Training on: {device}")

# Load the throw dataset generated by ThrowSim
df = pd.read_csv("build/throw_results.csv")
inputs = torch.tensor(df[["vx0", "vy0", "mass"]].values, dtype=torch.float32).to(device)
targets = torch.tensor(df[["final_x", "final_y", "maxHeight", "timeToLand", "bounceCount", "apexTime", "finalVx"]].values, dtype=torch.float32).to(device)
inputs = add_engineered_features(inputs)

# Train/val/test split (70/15/15), shuffled. Val drives early stopping
# (so "best val loss" is somewhat cherry-picked - it's the best of many
# checkpoints on that exact set). Test is never touched until the very
# end, so it gives an honest, unbiased read on generalization.
torch.manual_seed(42)
n = inputs.shape[0]
perm = torch.randperm(n)
train_split = int(n * 0.7)
val_split = int(n * 0.85)
train_idx, val_idx, test_idx = perm[:train_split], perm[train_split:val_split], perm[val_split:]

train_inputs, train_targets = inputs[train_idx], targets[train_idx]
val_inputs, val_targets = inputs[val_idx], targets[val_idx]
test_inputs, test_targets = inputs[test_idx], targets[test_idx]

# Normalize inputs using train-set stats only (avoid leaking val/test info)
input_mean = train_inputs.mean(dim=0)
input_std = train_inputs.std(dim=0)
train_inputs = (train_inputs - input_mean) / input_std
val_inputs = (val_inputs - input_mean) / input_std
test_inputs = (test_inputs - input_mean) / input_std

# Mini-batches instead of one full-batch gradient step per epoch. At
# hundreds of thousands of rows, full-batch meant one update per epoch,
# which is a brutal waste of compute - this gives far more updates per
# pass through the data, converging faster and often to a better result.
batch_size = 2048
train_dataset = TensorDataset(train_inputs, train_targets)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# Instantiate the model, loss function, and optimizer
model = ImprovedNeuralNetwork().to(device)
# Huber loss instead of MSE: quadratic near zero but linear for large
# errors, so a handful of extreme throws (large vx/vy/mass combos) don't
# dominate the gradient the way squared error would.
criterion = nn.HuberLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)

# Drops LR by 10x when val loss stalls, so late-stage training can settle
# instead of oscillating around a coarse fixed step size. Scheduler
# patience is shorter than early-stopping patience so it gets a chance
# to act before training just stops.
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="min", factor=0.75, patience=55)

# Train, with early stopping on val loss
epochs = 50000
patience = 100
best_val_loss = float("inf")
best_state = None
epochs_no_improve = 0

for epoch in range(epochs):
    model.train()
    # Accumulate on-device and only call .item() once per epoch instead of
    # once per batch - .item() forces a CPU/MPS sync, which stalls the
    # async pipeline and badly hurts throughput if done every batch.
    epoch_loss_sum = torch.zeros((), device=device)
    epoch_sample_count = 0
    for batch_inputs, batch_targets in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_inputs)
        loss = criterion(outputs, batch_targets)
        loss.backward()
        optimizer.step()
        epoch_loss_sum += loss.detach() * batch_inputs.size(0)
        epoch_sample_count += batch_inputs.size(0)
    train_loss = (epoch_loss_sum / epoch_sample_count).item()

    model.eval()
    with torch.no_grad():
        val_outputs = model(val_inputs)
        val_loss = criterion(val_outputs, val_targets)

    prev_lr = optimizer.param_groups[0]["lr"]
    scheduler.step(val_loss.item())
    new_lr = optimizer.param_groups[0]["lr"]
    if new_lr != prev_lr:
        print(f"Epoch {epoch + 1}: learning rate reduced {prev_lr:.6f} -> {new_lr:.6f}")

    if (epoch + 1) % 20 == 0:
        print(f"Epoch {epoch + 1}/{epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss.item():.4f}")

    if val_loss.item() < best_val_loss:
        best_val_loss = val_loss.item()
        best_state = copy.deepcopy(model.state_dict())
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= patience:
            print(f"Early stopping at epoch {epoch + 1} (no val improvement for {patience} epochs)")
            break

model.load_state_dict(best_state)
print(f"Final train loss: {train_loss:.4f}")
print(f"Best val loss: {best_val_loss:.4f}")

# Honest final number: test set was never used for early stopping or any
# other decision during training, so this isn't cherry-picked like the
# val loss above can be.
model.eval()
with torch.no_grad():
    test_outputs = model(test_inputs)
    test_loss = criterion(test_outputs, test_targets)
print(f"Test loss (held out, never used during training): {test_loss.item():.4f}")

# Save as CPU tensors so the checkpoint loads fine on any machine,
# regardless of whether it has MPS/CUDA available.
torch.save({
    "model_state_dict": {k: v.cpu() for k, v in model.state_dict().items()},
    "input_mean": input_mean.cpu(),
    "input_std": input_std.cpu(),
}, "models/ImprovedNeuralNetwork.pth")
print("Saved weights + input normalization stats to models/ImprovedNeuralNetwork.pth")
