import copy
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim

from models.ImprovedNeuralNetwork import ImprovedNeuralNetwork

# Load the throw dataset generated by ThrowSim
df = pd.read_csv("build/throw_results.csv")
inputs = torch.tensor(df[["vx0", "vy0", "mass"]].values, dtype=torch.float32)
targets = torch.tensor(df[["final_x", "final_y", "maxHeight"]].values, dtype=torch.float32)

# Train/val split (80/20), shuffled
torch.manual_seed(42)
n = inputs.shape[0]
perm = torch.randperm(n)
split = int(n * 0.8)
train_idx, val_idx = perm[:split], perm[split:]

train_inputs, train_targets = inputs[train_idx], targets[train_idx]
val_inputs, val_targets = inputs[val_idx], targets[val_idx]

# Normalize inputs using train-set stats only (avoid leaking val-set info)
input_mean = train_inputs.mean(dim=0)
input_std = train_inputs.std(dim=0)
train_inputs = (train_inputs - input_mean) / input_std
val_inputs = (val_inputs - input_mean) / input_std

# Instantiate the model, loss function, and optimizer
model = ImprovedNeuralNetwork()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Train, with early stopping on val loss
epochs = 50000
patience = 50
best_val_loss = float("inf")
best_state = None
epochs_no_improve = 0

for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(train_inputs)
    train_loss = criterion(outputs, train_targets)
    train_loss.backward()
    optimizer.step()

    model.eval()
    with torch.no_grad():
        val_outputs = model(val_inputs)
        val_loss = criterion(val_outputs, val_targets)

    if (epoch + 1) % 20 == 0:
        print(f"Epoch {epoch + 1}/{epochs}, Train Loss: {train_loss.item():.4f}, Val Loss: {val_loss.item():.4f}")

    if val_loss.item() < best_val_loss:
        best_val_loss = val_loss.item()
        best_state = copy.deepcopy(model.state_dict())
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= patience:
            print(f"Early stopping at epoch {epoch + 1} (no val improvement for {patience} epochs)")
            break

model.load_state_dict(best_state)
print(f"Final train loss: {train_loss.item():.4f}")
print(f"Best val loss: {best_val_loss:.4f}")

torch.save({
    "model_state_dict": model.state_dict(),
    "input_mean": input_mean,
    "input_std": input_std,
}, "models/ImprovedNeuralNetwork.pth")
print("Saved weights + input normalization stats to models/ImprovedNeuralNetwork.pth")
